services:
  - type: web
    name: web-mahanatours
    env: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
